### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by alex-ozdemir** [benjaminkiesl/drat2er#2]
Hey there,

I believe that during the implementations of backwards parsing & compression, a few files were forgotten. Specifically, `proof_reverser.cc` and `unused_clause_eliminator.cc`.

If you checkout master and try to configure using CMake, the following error is produced:

```
CMake Error at CMakeLists.txt:20 (add_library):
  Cannot find source file:

    src/proof_reverser.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
```

**Comment by benjaminkiesl** [comment]
Hi Alex,

Thanks for the bug report! You are right, I had forgotten to "git add" the source and header files for proof_reverser and unused_claues_eliminator. Please let me know in case drat2er does still not compile on your system.

Best wishes,
Benjamin
